import Content from "@/components/Content/Content";
import { Header } from "@/components/Header/Header";
import Card from "@/components/ui/Card/Card";
import { Box } from "@chakra-ui/react";
import classNames from "classnames";
import Image from "next/image";
import styles from './contracts-and-payments.module.css';
import './contracts-and-payments.css';
import { ContractsAndPaymentsContent } from "./components/contracts-and-payments";
import ProtectedRoute from "@/components/ProtectedRoute";

const cx = classNames.bind(styles);

interface IContractsAndPayments {}

export const metadata = {
  title: "Contracts & Payments - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

const homeCardData = [
  {
    title: "New Contracts this Week",
    description: "2",
    className: cx(styles.card, { "border-b-brand-primary": true }),
    cardImage: <Image src="/images/contracts-02.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
  {
    title: "New Contracts this Month",
    description: "10",
    className: cx(styles.card, { "border-b-brand-primary": true }),
    cardImage: <Image src="/images/contracts-02.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
  {
    title: "Contracts with balances",
    description: "5",
    className: cx(styles.card, { "border-b-neutrals-medium": true }),
    cardImage: <Image src="/images/invoice-03.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
  {
    title: "Contract value this month",
    description: "15",
    className: cx(styles.card, { "border-b-brand-secondary": true }),
    cardImage: <Image src="/images/analysis-text-link.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
];

const ContractsAndPayments: React.FC<IContractsAndPayments> = () => {
  return (
    <ProtectedRoute>
      <Header title="Contracts & Payments" subtitle="Contracts Overview">
        <Box className="flex flex-row space-x-3">
          {homeCardData.map((card, index) => (
            <Card
              key={index}
              title={card.title}
              description={card.description}
              className={card.className}
              titleClassName="text-sm"
              descriptionClassName="text-3xl font-medium mt-4"
              cardImage={card.cardImage}
            />
          ))}
        </Box>
      </Header>
      <Content className="space-y-4 !p-0">
        <ContractsAndPaymentsContent />
      </Content>
    </ProtectedRoute>
  )
};

export default ContractsAndPayments;