import Content from "@/components/Content/Content";
import { Header } from "@/components/Header/Header";
import Card from "@/components/ui/Card/Card";
import { Box } from "@chakra-ui/react";
import classNames from "classnames";
import Image from "next/image";
import styles from './vehicle-management.module.css';
import './vehicle-management.css';
import { Vehicles } from "./components/vehicles";
import ProtectedRoute from "@/components/ProtectedRoute";

const cx = classNames.bind(styles);

interface IVehicleManagement {}

export const metadata = {
  title: "Vehicle Management - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

const homeCardData = [
  {
    title: "Total Car Park",
    description: "2",
    className: cx(styles.card, { "border-b-brand-primary": true }),
    cardImage: <Image src="/images/garage.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
  {
    title: "Vehicle Orders Placed",
    description: "10",
    className: cx(styles.card, { "border-b-brand-primary": true }),
    cardImage: <Image src="/images/file-02.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
  {
    title: "Vehicles in Transit",
    description: "5",
    className: cx(styles.card, { "border-b-neutrals-medium": true }),
    cardImage: <Image src="/images/car-time.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
  {
    title: "Vehicles Handover this Month",
    description: "15",
    className: cx(styles.card, { "border-b-brand-secondary": true }),
    cardImage: <Image src="/images/agreement.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
  },
];

const VehicleManagement: React.FC<IVehicleManagement> = () => {
  return (
    <ProtectedRoute>
      <Header title="Vehicle Management" subtitle="Carpark Overview">
        <Box className="flex flex-row space-x-3">
          {homeCardData.map((card, index) => (
            <Card
              key={index}
              title={card.title}
              description={card.description}
              className={card.className}
              titleClassName="text-sm"
              descriptionClassName="text-3xl font-medium mt-4"
              cardImage={card.cardImage}
            />
          ))}
        </Box>
      </Header>
      <Content className="space-y-4 !p-0">
        <Vehicles />
      </Content>
    </ProtectedRoute>
  )
};

export default VehicleManagement;