import { JSX } from 'react';
import styles from './login.module.css';

type LoginLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Login - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }: LoginLayoutProps): JSX.Element {
  return (
    <div className={styles.login}>
      {children}
    </div>
  );
}
