import Content from "@/components/Content/Content";
import { Header } from "@/components/Header/Header";
import styles from './Engagement.module.css';
import classNames from "classnames";
import ProtectedRoute from "@/components/ProtectedRoute";

interface IEngagement {}

export const metadata = {
  title: "Engagement - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

const Engagement: React.FC<IEngagement> = () => {
  return (
    <ProtectedRoute>
      <Header title="Offers" subtitle="Offers Overview" />
      <Content />
    </ProtectedRoute>
  )
};

export default Engagement;