import Content from "@/components/Content/Content";
import { Header } from "@/components/Header/Header";
import styles from './contracts-and-payments.module.css';
import classNames from "classnames";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata = {
  title: "Administration - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

interface IAdministration {}

const Administration: React.FC<IAdministration> = () => {
  return (
    <>
      <ProtectedRoute>
        <Header title="Administration" subtitle="Overview" />
        <Content />
      </ProtectedRoute>
    </>
  )
};

export default Administration;