import Content from "@/components/Content/Content";
import { Header } from "@/components/Header/Header";
import ProtectedRoute from "@/components/ProtectedRoute";
import { ActionIcon } from "@mantine/core";
import Image from "next/image";

interface IDashboard {}

export const metadata = {
  title: "Dashboard - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

const Dashboard: React.FC<IDashboard> = () => {
  return (
    <>
      <ProtectedRoute>
        <Header title="Hello Yong Soo-Yun" subtitle="Service Advisor | Aston Martin Seoul" />
        <Content />
      </ProtectedRoute>
    </>
  )
};

export default Dashboard;