import Content from "@/components/Content/Content";
import { Header } from "@/components/Header/Header";
import Card from "@/components/ui/Card/Card";
import { Box } from "@chakra-ui/react";
import classNames from "classnames";
import Image from "next/image";
import { Orders } from "./components/orders";
import styles from './order-management.module.css';
import './order-management.css';
import ProtectedRoute from "@/components/ProtectedRoute";
import { formatNumberWithCommas } from "@/utils/common";

const cx = classNames.bind(styles);

interface IOrderManagement {}

export const metadata = {
  title: "Order Management - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

const OrderManagement: React.FC<IOrderManagement> = () => {
  const homeCardData = [
    {
      title: "New Orders this week",
      description: "3",
      className: cx(styles.card, { "border-b-brand-primary": true }),
      cardImage: <Image src="/images/garage.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
    },
    {
      title: "New Orders this month",
      description: "12",
      className: cx(styles.card, { "border-b-brand-primary": true }),
      cardImage: <Image src="/images/file-02.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
    },
    {
      title: "Orders Delivered this month",
      description: "8",
      className: cx(styles.card, { "border-b-neutrals-medium": true }),
      cardImage: <Image src="/images/car-time.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
    },
    {
      title: "Order Value this month",
      description: `${formatNumberWithCommas(3000000000)}`,
      className: cx(styles.card, { "border-b-brand-secondary": true }),
      cardImage: <Image src="/images/agreement.svg" alt="garge" width={70} height={90} className="absolute right-0 top-2 z-10" />
    },
  ];
  
  return (
    <ProtectedRoute>
      <Header title="Order Management" subtitle="Order Overview">
        <Box className="flex flex-row space-x-3">
          {homeCardData.map((card, index) => (
            <Card
              key={index}
              title={card.title}
              description={card.description}
              className={card.className}
              titleClassName="text-sm"
              descriptionClassName="text-3xl font-medium mt-4"
              cardImage={card.cardImage}
            />
          ))}
        </Box>
      </Header>
      <Content>
        <Orders />
      </Content>
    </ProtectedRoute>
  )
};

export default OrderManagement;