import ProtectedRoute from "@/components/ProtectedRoute";
import { ContactLifeCycleContent } from "./components/content";
import { IActionMenuItem } from "@/components/ActionMenu/action-menu";

interface IContactLifeCycle {}

export const metadata = {
  title: "Contact Life Cycle - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

const ContactLifeCycle: React.FC<IContactLifeCycle> = () => {
  return (
    <>
      <ProtectedRoute>
        <ContactLifeCycleContent />
      </ProtectedRoute>
    </>
  )
};

export default ContactLifeCycle;