import styles from './home.module.css';

export const metadata = {
  title: "Home - Lagonda - Aston Martin",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.home}>
      {children}
    </div>
  );
}
